version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=production
    env_file:
      - .env
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${WEB_PORT}:80"
      - "${SSL_PORT}:443"
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ./certbot-init/conf:/etc/letsencrypt
      - ./certbot-init/www:/var/www/certbot
    environment:
      - WEB_PORT=${WEB_PORT}
      - SSL_PORT=${SSL_PORT}
    depends_on:
      - web
  certbot:
    build: ./certbot-init/
    volumes:
      - ./certbot-init/conf:/etc/letsencrypt
      - ./certbot-init/www:/var/www/certbot
      - ~/.ddnsnow:/root/.ddnsnow
