name: Deploy Production

on:
  push:
    branches: [ main ]

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Production with build check
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd kakeibo_on_rails &&
            git checkout . &&
            git fetch origin main &&

            # サービスを停止しておく
            docker-compose -f docker-compose.production.yml down &&

            # Gemfile関連に変更があるか確認
            if git diff --name-only HEAD..origin/main | grep "Gemfile\|Gemfile.lock"; then
              echo "Gemfile changes detected, building containers..."
              git pull origin main &&
              docker-compose -f docker-compose.production.yml build &&
              docker-compose -f docker-compose.production.yml up -d
            else
              echo "No Gemfile changes, regular deploy"
              git pull origin main &&
              docker-compose -f docker-compose.production.yml up -d
            fi
          '
